name: Update WakaTime Calendar

on:
  schedule:
    # Каждый день в 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # позволяет запускать вручную

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run calendar generator
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: python src/wakatime.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update coding calendar [skip ci]"
          file_pattern: coding_dashboard.png
